#!/bin/bash

# Parse command line options
CONVENTIONAL=false

while [[ $# -gt 0 ]]; do
  case $1 in
    -c|--conventional)
      CONVENTIONAL=true
      shift
      ;;
    *)
      shift
      ;;
  esac
done

SCRIPT_DIR="/usr/local/lib/git-ai-commit"
CURRENT_DIR="$(pwd)"

COMMAND="import os; os.chdir('$CURRENT_DIR'); import ai_commit_message; ai_commit_message.main()"
ARGS="--commit"

if [ "$CONVENTIONAL" = true ]; then
  ARGS="$ARGS --conventional"
fi

(cd "$SCRIPT_DIR" && PYTHONPATH="$SCRIPT_DIR" poetry run python -c "$COMMAND" $ARGS)
STATUS=$?
if [ $STATUS -eq 0 ]; then
    git --no-pager log -1 --pretty=format:"%h"
fi
exit $STATUS 
